Branch1
mwakiogeofrey/PORTFOLIO-PROJECT pull request #1
Opened 2023-01-11 23:48 UTC by mwakiogeofrey

The project was about making a portfolio about mysef

2023-01-12 01:28 UTC, IngDavidTM requested changes
Hi @mwakiogeofrey  🙋‍♂️, 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code

## :no_entry:  Invalid Code Review Request :no_entry: 

You did a good job implementing the README file :+1: but as a general requirement you should customize the file because it would make your project looks more professional and this is one of the first things that hiring managers or your potential colleagues will check when considering you for a position on their team. To learn more you could read [Document your repo in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/clean_repo.md)
[Here](https://github.com/microverseinc/readme-template) you can find the template that you can follow.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready :inbox_tray: 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 14:38 UTC, mukhammadrizooff requested changes
Hi @mwakiogeofrey, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 14:38 UTC, mukhammadrizooff commented on index.html
> +        </div>
- [ ] [REQUIRED] Please implement my suggestions below:

  * Please remove the top side(`time`, `wi-fi` icon and black dot) of your web page, you can see compare the picture below=> 
![image](https://user-images.githubusercontent.com/63915024/212089328-4817f282-f000-4951-b736-ca2f2c8cbc4a.png)


  * Please, your `logo` should be on the left (✔️ ) and has an `a` link (`a` tag). This is for three reasons: `convention`, `semantics`, and `user` experience(`UX`). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info 👍🏼 

  * Please change the `div` tag on line `15` to the `nav` tag and also change `<div class="box">` to <header class="box">` because  `Header` elements should be inside of the `nav` tag because the `nav` tag is for semantics reasons and is the right position (✔️) for convention and `user` experience for mobile devices 😃 

```html
<header>
    <nav>
        <a>Website Logo</a>
        <!-- Main Navigation inside <header> -->
        <ul>
            <li></li>
        </ul>
    </nav>
</header>
```

2023-01-12 14:38 UTC, mukhammadrizooff commented on index.html
> +        <div class="box1">
- [ ] [OPTIONAL] In my opinion `section` tag is more semantic than the `div` tag in this position 👍🏼

2023-01-12 14:38 UTC, mukhammadrizooff commented on index.html
> +                </h3>
- [ ] [REQUIRED] Good job so far! The paragraph (e.g., `"I can help you build a product ..."`) should be a `p` tag 👍🏼

2023-01-12 14:38 UTC, mukhammadrizooff commented on index.html
> +                    </ul>
- [ ] [REQUIRED] Nice work but the list of icons should use a `ul`(✔️) tag to group them, and `li`(✔️) per icon; each icon has a link (`a` tag ❌). Please implement my suggestions 🙏🏼 ||✔️ => Done; ❌ => Not implemented

2023-01-12 14:38 UTC, mukhammadrizooff commented on style.css
> +}
- [ ] [REQUIRED] Please implement my suggestions below:

  * Please add the correct `Property` and `Value` to your text elements. Please add the correct `font-family` to `.Intro {...}` => `font-family: 'Crete Round';`

  * Please add the correct `Property` and `Value` to your text elements. Please add the correct `font-family` to `.Info {...}` => `font-family: 'Roboto';`

  * Please add the correct `Property` and `Value` to your text elements. Please add the correct `font-family` to `.Information {...}` => `font-family: 'Poppins';`

![image](https://user-images.githubusercontent.com/63915024/212093680-0b1cfaf4-652e-4bee-85a6-cdf6d2b1ad68.png)

2023-01-12 14:38 UTC, mukhammadrizooff commented on style.css
> +}
- [ ] [REQUIRED] Good job so far! Please remove all `BLACK` `DOTS` on your social links 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/212094417-c6085ed0-ddc6-48d5-8c4e-12f4e3520fc6.png)

2023-01-12 14:38 UTC, mukhammadrizooff commented on style.css
> +}
- [ ] [REQUIRED] Good job so far! Please try to make the `figure` in your project look like the `figure` in [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=48%3A27&t=KDvpPZCqtO3PrB4d-0)🙏🏼

![image](https://user-images.githubusercontent.com/63915024/212094901-5f38b123-527c-40a7-9ee1-aa4c0f64cdc6.png)

2023-01-12 22:25 UTC, vickymarz requested changes
Hi @mwakiogeofrey, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯
 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- I will recommend you always write a descriptive pull request title and branch name which is a perfect representation of the changes or features you are working on. Naming a PR feature is not described as a PR title and branch name. Kindly note that this is a reason for the invalidation of your project.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 22:25 UTC, vickymarz commented on index.html
> +                        <img src="images/Social Media.png" alt="social media">
- [ ] Nice work but the list of icons should use a `<ul>` tag to group them, and `<li>` per icon; with each icon wrapped in a link (`<a>` tag ) as the previous reviewer has suggested.

your list of icons should be actual icons that will be clickable to link to your social media icons. Please do not group all the social icons images and past as an entire image as you have done here 👍🏽

2023-01-12 22:25 UTC, vickymarz commented on style.css
> +.info {
- [ ]  Please implement my suggestions below as suggested by the previous reviewer:

Please add the correct Property and Value to your text elements. Please add the correct font-family to .Intro {...} => `font-family: 'Crete Round`';

Please add the correct Property and Value to your text elements. Please add the correct font-family to .Info {...} => `font-family: 'Roboto`';

Please add the correct Property and Value to your text elements. Please add the correct font-family to .Information {...} => `font-family: 'Poppins'`;

you can get the fonts from [google font](https://fonts.google.com/) and import them into your stylesheet for use 👍🏽

2023-01-13 14:56 UTC, jerryowusu approved these changes
Hi @mwakiogeofrey , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![CookedDelectableDolphin-size_restricted](https://user-images.githubusercontent.com/65233860/212350114-0e6482b9-c38e-4bbd-8e1f-91336cb0e44e.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Great effort in making the required changes :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 14:59 UTC, merged